services:
  - type: web
    name: macroc-team-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_PROVIDER
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        sync: false
      - key: SPACEBYTE_BASE_URL
        sync: false
      - key: SPACEBYTE_API_TOKEN
        sync: false
      - key: SPACEBYTE_TOKEN_NAME
        sync: false
      - key: CONTACT_RECEIVER_EMAIL
        sync: false
